#!/bin/bash

# IP parsing (good enough)

raw="$1"
ip=$(echo "$raw" | grep -Po 'ip.+?\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}' | cut -c 4-)
banner=$(echo "$raw" | grep -Po 'banner.+?2.*' | cut -c 8-)
banner=${banner:: -2}
timestamp=$(date +%s)

# Payloads. Add your scripts here. This sample payload probes for anon access and
# saves the complete exchange to the JSON log.

openftp4=$(echo -e "user anonymous anonymous@\nquit\n" | timeout -k1 15 ftp -v -d -n "$ip" 2>/dev/null | tr '\n' '|')

# Output result

if [[ $openftp4 =~ "230 " ]]; then
  echo "{\"ip\":\"$ip\",\"timestamp\":$timestamp,\"banner\":\"$banner\",\"exchange\":\"$openftp4\"}," >> "./openftp4.json"
fi
