#!/bin/bash

ip="$1"
timestamp=$(date +%s)

# Payloads. Add your scripts here. This sample payload probes for anon access and
# saves the complete exchange to the JSON log.

openftp4=$(echo -e "user anonymous anonymous@\nquit\n" | timeout -k1 10 ftp -v -n "$ip" 2>/dev/null | tr '\n' '%' | sed 's/%/\\n/g')

# Output result

if [[ $openftp4 =~ "230 " ]]; then
  echo "{\"ip\":\"$ip\",\"ts\":$timestamp,\"lg\":\"$openftp4\"}," >> "./openftp4.json"
else
  echo "{\"ip\":\"$ip\",\"ts\":$timestamp,\"lg\":\"error\"}," >> "./openftp4.json"
fi
